backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery" # This creates a folder for each photo entry
    create: true # This allows you to add NEW entries
    extension: "json"
    format: "json"
    slug: "{{title}}" # The filename will be the title
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "src", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }